# Site Info
title:              "silentsokolov's blog"
description:        "blog about software development and geek's lifestyle"
keywords:           "blog,personal,development,backend,python,golang,go,rust,gaming"
author_name:        "silentsokolov"
logo_url:           https://silentsokolov.github.io/assets/avatar.png

# Site Settings
url:                https://silentsokolov.github.io # main url
baseurl:            /
permalink:          /:title # Post permalink
timezone:           Europe/Moscow # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            false  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "Gemfile", "googlee2ccc40699d300c8.html", "yandex_db4fbe6dcc657df9.html" ]
plugins:
  - jekyll-sitemap
  - jekyll-remote-theme

remote_theme: heiswayi/the-plain
