# Site Info
title:              "Silent"
description:        "I do not know what's going on"
author_name:        "silentsokolov" # change this to your name
logo_url:           https://raw.githubusercontent.com/silentsokolov/silentsokolov.github.io/master/images/common/avatar.png # Get it from GitHub API: https://api.github.com/users/<username>

# Site Settings
url:                https://silentsokolov.github.io # main url
baseurl:            /
permalink:          /:title # Post permalink
timezone:           Europe/Moscow # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones
mathjax:            true  # enables support for mathjax - set to 'false' to disable

# Site Build
highlighter:        rouge
markdown:           kramdown
kramdown:
    input:          GFM
sass:
    style:          :compressed

# Other Params
include:            [ "robots.txt" ]
exclude:            [ "Gemfile" ]
plugins:
  - jekyll-sitemap
  - jekyll-remote-theme

remote_theme: heiswayi/the-plain
